project:
  type: website

website:
  title: "Carolyn Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects 
      - href: courses.qmd
        text: Courses
  page-footer: 
    right: "&copy; 2024, Carolyn Wang"

format:
  html:
    theme: cosmo
    css: styles.css
    cold-fold: false 
    toc: true # globally everything with headings has TOC
    # can change locally in each file (toc: FALSE)

editor: visual

execute: 
  freeze: auto # look at old version if there are no changes

